services:
  app:
    build: .
    container_name: takimoto_library_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: takimoto_library_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: takimoto
      MYSQL_DATABASE: takimoto_library
      MYSQL_USER: takimoto_user
      MYSQL_PASSWORD: takimoto
      TZ: Asia/Tokyo
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4
    container_name: takimoto_library_adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
